---
- name: working with tags
  hosts: dev
  become: true
  gather_facts: false
  tasks:
          - name: writing 1st tag
            copy:
                    content: "Hello"
                    dest: /var/www/html/index.html
            tags:
                    - alpha
                    - never
          - name: writing 2nd tag
            copy:
                    content: "Bye Bye"
                    dest: /var/www/html/index.html
            tags:
                    - beta
                    - never
